#! /bin/sh

/bin/mount -a

echo "
            _ _ _ _ _ _ _ _ _ _ _ _
            \  _  _   _  _ _ ___
            / /__/ \ |_/
           / __   /  -  _ ___
          / /  / /  / /
  _ _ _ _/ /  /  \_/  \_ ______
___________\___\__________________
"
for initscript in /etc/init.d/S[0-9][0-9]*
do
	if [ -x $initscript ] ;
	then
		echo "[RCS]: $initscript"
		$initscript
	fi
done

if [ -x /usr/sbin/telnetd ];
then
        telnetd&
fi


mount -t jffs2 /dev/mtdblock4 /mnt/mtd/
if [ "$?" != "0" ]; then
       echo "No JFFS2 fs info on mtdblock4, creating it..."
        flash_eraseall /dev/mtd4
        mount -t jffs2 /dev/mtdblock4 /mnt/mtd
fi


if [ -e /usr/update/file/boot.sh ]; then
	cp /usr/update/file/boot.sh /etc/init.d
fi

sh /etc/init.d/boot.sh


